kind: pipeline
type: docker
name: default

steps:
- name: Build Site
  image: plugins/hugo
  settings:
    hugo_version: 0.89.2
    extended: true
    config: config.yaml
    validate: true
  commands:
    - git submodule update --init --recursive
    - /bin/drone-hugo
  when:
    branch: main

- name: Deploy to VPS
  image: appleboy/drone-scp
  settings:
    host:
      from_secret: ssh_host
    target:
      from_secret: ssh_target
    source: public/*
    username:
      from_secret: ssh_username
    key:
      from_secret: ssh_key
    port:
      from_secret: ssh_port
  when:
    branch: main

- name: Send TG Notification
  image: appleboy/drone-telegram
  settings:
    token:
      from_secret: tg_token
    to:
      from_secret: tg_id
    format: markdown
    message: >
      {{#success build.status}}
        ✅  Build for `{{repo.name}}` was *successful*!

        📝  {{ commit.message }}

        🌐  [Output]({{build.link}})
      {{else}}
        ❌  Build for `{{repo.name}}` has *FAILED*!

        📝  {{ commit.message }}

        🌐  [Output]({{build.link}})
      {{/success}}
  when:
    status: [ success, failure ]