kind: pipeline
type: docker
name: default

steps:
- name: Build Site (main)
  image: plugins/hugo
  settings:
    hugo_version: 0.100.1
    extended: true
    config: config.yaml
    validate: false
  commands:
    - git submodule update --init --recursive
    - /bin/drone-hugo
  when:
    branch: main

- name: Deploy to VPS (main)
  image: appleboy/drone-scp
  settings:
    host:
      from_secret: ssh_host
    target:
      from_secret: ssh_target
    source: public/*
    username:
      from_secret: ssh_username
    key:
      from_secret: ssh_key
    port:
      from_secret: ssh_port
  when:
    branch: main

- name: Build Site (staging)
  image: plugins/hugo
  settings:
    hugo_version: 0.100.1
    extended: true
    config: config.yaml
    validate: false
  commands:
    - git submodule update --init --recursive
    - /bin/drone-hugo
  when:
    branch: staging

- name: Deploy to VPS (staging)
  image: appleboy/drone-scp
  settings:
    host:
      from_secret: ssh_host
    target:
      from_secret: ssh_target
    source: public/*
    username:
      from_secret: ssh_username
    key:
      from_secret: ssh_key
    port:
      from_secret: ssh_port
  when:
    branch: staging

- name: Send TG Notification
  image: appleboy/drone-telegram
  settings:
    token:
      from_secret: tg_token
    to:
      from_secret: tg_id
    format: markdown
    message: "{{#success build.status}}✅  Build for `{{repo.name}}` was *successful*!{{else}}❌  Build for `{{repo.name}}` has *FAILED*!{{/success}} \n🌐  [Output]({{build.link}})\n📝  Commit: {{ commit.message }}"
  when:
    status: [ success, failure ]
