steps:
- name: Build Site (main)
  image: hugomods/hugo:exts-0.127.0
  commands:
    - git submodule update --init --recursive
    - hugo
  when:
    branch: main
    event: [ push, manual ]

- name: Deploy to VPS (main)
  image: appleboy/drone-scp
  settings:
    host:
      from_secret: ssh_host
    target: /var/www/blog
    source: public/*
    username:
      from_secret: ssh_username
    key:
      from_secret: ssh_key
    port:
      from_secret: ssh_port
  when:
    branch: main
    event: [ push, manual ]

- name: Build Site (staging)
  image: hugomods/hugo:exts-0.127.0
  commands:
    - git submodule update --init --recursive
    - hugo
  when:
    branch: staging

- name: Deploy to VPS (staging)
  image: appleboy/drone-scp
  settings:
    host:
      from_secret: ssh_host
    target: /var/www/staging
    source: public/*
    username:
      from_secret: ssh_username
    key:
      from_secret: ssh_key
    port:
      from_secret: ssh_port
  when:
    branch: staging
    event: [ push, manual ]

- name: Send TG Notification
  image: appleboy/drone-telegram
  settings:
    token:
      from_secret: tg_token
    to:
      from_secret: tg_id
    format: markdown
    message: "{{#success build.status}}✅  Build for `{{repo.name}}` was *successful*!{{else}}❌  Build for `{{repo.name}}` has *FAILED*!{{/success}} \n🌐  [Output]({{build.link}})\n📝  Commit: {{ commit.message }}"
  when:
    status: [ success, failure ]
    event: [ push, manual ]