steps:
- name: Build Site (main)
  image: hugomods/hugo:exts-0.153.3
  commands:
    - git submodule update --init --recursive
    - hugo
  when:
    - branch: main
      event: [push, manual]

- name: Deploy to VPS (main)
  image: appleboy/drone-scp
  settings:
    host:
      from_secret: ssh_host
    target: /var/www/blog
    source: public/*
    username:
      from_secret: ssh_username
    key:
      from_secret: ssh_key
    port:
      from_secret: ssh_port
  when:
    - branch: main
      event: [push, manual]

- name: Build Site (staging)
  image: hugomods/hugo:exts-0.153.3
  commands:
    - git submodule update --init --recursive
    - hugo
  when:
    - branch: staging
      event: [push, manual]

- name: Deploy to VPS (staging)
  image: appleboy/drone-scp
  settings:
    host:
      from_secret: ssh_host
    target: /var/www/staging
    source: public/*
    username:
      from_secret: ssh_username
    key:
      from_secret: ssh_key
    port:
      from_secret: ssh_port
  when:
    - branch: staging
      event: [push, manual]

- name: Notify Success
  image: appleboy/drone-telegram
  settings:
    token:
      from_secret: tg_token
    to:
      from_secret: tg_id
    format: markdown
    message: "✅  Build for `${CI_REPO_NAME}` was *successful*!\n🌐  [Output](${CI_PIPELINE_URL})\n📝  Commit: ${CI_COMMIT_MESSAGE}"
  when:
    - event: [push, manual]
      status: [success]

- name: Notify Failure
  image: appleboy/drone-telegram
  settings:
    token:
      from_secret: tg_token
    to:
      from_secret: tg_id
    format: markdown
    message: "❌  Build for `${CI_REPO_NAME}` has *FAILED*!\n🌐  [Output](${CI_PIPELINE_URL})\n📝  Commit: ${CI_COMMIT_MESSAGE}"
  when:
    - event: [push, manual]
      status: [failure]