baseurl: https://blog.fuzzymistborn.com
languageCode: en-us
theme: hugo-theme-stack
paginate: 10
title: Random Musings

# Change it to your Disqus shortname before using
#disqusShortname: hugo-theme-stack

# GA Tracking ID
#googleAnalytics:

# Theme i18n support
# Available values: en, fr, id, ja, ko, pt-br, zh-cn, es, de, nl
DefaultContentLanguage: en

permalinks:
    post: /:slug/
    page: /:slug/

params:
    mainSections:
        - post
    featuredImageField: image
    rssFullContent: true
    favicon: /images/favicon.ico

    footer:
        since: 2021
        customText:

    dateFormat:
        published: Jan 02, 2006
        lastUpdated: Jan 02, 2006 15:04 EST

    sidebar:
        emoji: 
        subtitle: Home automation, Linux, and other nerdy things
        avatar:
            local: false
            src: /images/LegalBot_crop.jpg

    article:
        math: false
        license:
            enabled: false
            default: See a typo/mistake or something that could be improved?  Open an issue or PR on Github!

    comments:
        enabled: true
        provider: giscus
            repo: fuzzymistborn/blog
            repoID: MDEwOlJlcG9zaXRvcnkzNTY0NTcxMjQ=
            category: Blog Post Comments
            categoryID: DIC_kwDOFT8apM4CTUN7
            mapping: title
            strict: 0
            lightTheme: light
            darkTheme: dark
            reactionsEnabled: 1
            emitMetadata: 0
            inputPosition: top
            lang: en

        utterances:
            repo:
            issueTerm: pathname
            label:

        remark42:
            host:
            site:
            locale:

    widgets:
        enabled:
            - search
            - archives
            - tag-cloud

        archives:
            limit: 5

        tagCloud:
            limit: 10

    opengraph:
        twitter:
            # Your Twitter username
            site:

            # Available values: summary, summary_large_image
            card: summary_large_image

    defaultImage:
        opengraph:
            enabled: false
            local: false
            src: "/images/header.jpg"

    colorScheme:
        # Display toggle
        toggle: true

        # Available values: auto, light, dark
        default: auto

    imageProcessing:
        cover:
            enabled: true
        content:
            enabled: true

### Custom menu
### See https://docs.stack.jimmycai.com/configuration/custom-menu
### To remove about, archive and search page menu item, remove `menu` field from their FrontMatter
menu:
    main:
        - identifier: home
          name: Home
          url: /
          weight: -100
          params:
            icon: home
        - identifier: about
          name: About
          url: /about
          weight: -90
          params:
            icon: user
        - identifier: support
          name: Support
          url: /support
          weight: -80
          params:
            icon: gift
        - identifier: github
          name: Report an issue
          url: https://github.com/FuzzyMistborn/blog/issues
          weight: -70
          params:
            icon: github
        - identifier: rss
          name: RSS Feed
          url: https://blog.fuzzymistborn.com/post/index.xml
          weight: -70
          params:
            icon: rss

related:
    includeNewer: true
    threshold: 60
    toLower: false
    indices:
        - name: tags
          weight: 100

        - name: categories
          weight: 200

markup:
    highlight:
        noClasses: false
